name: Run C++ Tests

on:
  push:
    branches: [ "main" ]
  pull_request: # No branch filter means this runs for all PRs

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0

      - name: Configure CMake
        run: cmake -B build -S . -D YOGACPP_BUILD_TESTS=ON

      - name: Build project
        run: cmake --build build

      - name: Run tests
        working-directory: ./build
        run: ctest --output-on-failure
